# Generated by Django 4.1.3 on 2022-11-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=1000, verbose_name='ingredient')),
                ('amount', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='amount')),
                ('metrics', models.CharField(choices=[('mg', 'miligrams'), ('g', 'grams'), ('Kg', 'kilograms'), ('ml', 'mililiters'), ('L', 'liters'), ('Cup', 'cup'), ('Tspn', 'tea spoon'), ('Tblspn', 'table spoon')], default='g', max_length=6, verbose_name='metrics')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('steps', models.TextField(max_length=10000, verbose_name='steps')),
                ('duration', models.DecimalField(decimal_places=4, max_digits=4, verbose_name='duration')),
                ('calories', models.DecimalField(decimal_places=4, max_digits=4, verbose_name='calories')),
                ('servings', models.DecimalField(decimal_places=4, max_digits=4, verbose_name='servings')),
                ('ingredients', models.ManyToManyField(to='recipes.ingredient', verbose_name='Ingredients')),
            ],
        ),
    ]
