# Generated by Django 4.1.3 on 2022-11-30 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=1000, verbose_name='ingredient')),
                ('amount', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='amount')),
                ('metrics', models.CharField(choices=[('mg', 'miligram(s)'), ('g', 'gram(s)'), ('Kg', 'kilogram(s)'), ('ml', 'mililiter(s)'), ('L', 'liter(s)'), ('Cup', 'cup(s)'), ('Tspn', 'tea spoon(s)'), ('Tblspn', 'table spoon(s)'), ('Oz', 'Oz'), ('whole', 'Whole')], default='g', max_length=6, verbose_name='metrics')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('steps', models.TextField(max_length=10000, verbose_name='steps')),
                ('duration', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='duration(min)')),
                ('calories', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='calories')),
                ('servings', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='servings')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures', verbose_name='picture')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_author', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('ingredients', models.ManyToManyField(to='recipes.ingredient', verbose_name='Ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('comment', models.TextField(max_length=1000, verbose_name='comment')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.recipe', verbose_name='recipe')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_comments', to=settings.AUTH_USER_MODEL, verbose_name='writer')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(choices=[(1, '(1) Awful'), (2, '(2) Bad'), (3, '(3) Normal'), (4, '(4) Deliciuos'), (5, '(5) Amazing!')], max_length=10, verbose_name='stars')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ratings', to=settings.AUTH_USER_MODEL, verbose_name='rater')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star', to='recipes.recipe', verbose_name='recipe')),
            ],
        ),
    ]
