# Generated by Django 4.1.3 on 2022-11-30 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(choices=[('1', 'Awful'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Deliciuos'), ('5', 'Amazing!')], max_length=1, verbose_name='stars')),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='metrics',
            field=models.CharField(choices=[('mg', 'miligram(s)'), ('g', 'gram(s)'), ('Kg', 'kilogram(s)'), ('ml', 'mililiter(s)'), ('L', 'liter(s)'), ('Cup', 'cup(s)'), ('Tspn', 'tea spoon(s)'), ('Tblspn', 'table spoon(s)')], default='g', max_length=6, verbose_name='metrics'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='calories'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='duration',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='duration(min)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='servings'),
        ),
        migrations.CreateModel(
            name='RecipeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('comment', models.TextField(max_length=1000, verbose_name='comment')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.recipe', verbose_name='recipe')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_comments', to=settings.AUTH_USER_MODEL, verbose_name='writer')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
