# Generated by Django 4.1.3 on 2022-12-06 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe', verbose_name='recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ingredient'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.CharField(choices=[('1', '(1) Awful'), ('2', '(2) Bad'), ('3', '(3) Normal'), ('4', '(4) Deliciuos'), ('5', '(5) Amazing!')], max_length=10, verbose_name='stars'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True, verbose_name='calories'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='duration',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True, verbose_name='duration(min)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True, verbose_name='servings'),
        ),
    ]
