# Generated by Django 4.1.3 on 2022-12-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.CharField(choices=[('1', '(1) Awful'), ('2', '(2) Bad'), ('3', '(3) Normal'), ('4', '(4) Deliciuos'), ('5', '(5) Amazing!')], max_length=10, verbose_name='stars'),
        ),
    ]
