# Generated by Django 4.1.3 on 2022-12-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_recipe_recipecomment_recipe4com'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipecomment',
            old_name='recipe4com',
            new_name='recipe',
        ),
    ]
