# Generated by Django 4.1.3 on 2022-12-11 18:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_rating_stars_rating_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='metrics',
            field=models.CharField(choices=[('mg', 'miligram(s)'), ('g', 'gram(s)'), ('Kg', 'kilogram(s)'), ('pound', 'pound(s)'), ('ml', 'mililiter(s)'), ('L', 'liter(s)'), ('gallon', 'gallon(s)'), ('Cup', 'cup(s)'), ('Tspn', 'tea spoon(s)'), ('Tblspn', 'table spoon(s)'), ('Oz', 'Oz'), ('whole', 'Whole')], default='g', max_length=6, verbose_name='metrics'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=tinymce.models.HTMLField(max_length=10000, verbose_name='steps'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
