# Generated by Django 4.1.3 on 2022-12-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_ingredient_amount_alter_ingredient_metrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='metrics',
            field=models.CharField(choices=[('mg.', 'miligram(s)'), ('g.', 'gram(s)'), ('Kg.', 'kilogram(s)'), ('pound', 'pound(s)'), ('ml.', 'mililiter(s)'), ('L.', 'liter(s)'), ('gallon', 'gallon(s)'), ('Cup', 'cup(s)'), ('Tspn.', 'tea spoon(s)'), ('Tblspn.', 'table spoon(s)'), ('Oz.', 'Oz'), ('whole', 'Whole')], default='g', max_length=8, verbose_name='metrics'),
        ),
    ]
