# Generated by Django 4.1.3 on 2022-12-01 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_profile/photos', verbose_name='photo')),
                ('profile_type', models.CharField(choices=[('1', 'Grill lover'), ('2', 'Picnic enthusiast'), ('3', 'Vegatarian'), ('4', 'Meat Lover'), ('5', 'Pro Chief'), ('6', 'Just an average Chief'), ('7', 'Cooker on Holidays'), ('8', 'Alcocholic'), ('8', 'Candy crusher')], max_length=10, verbose_name='types')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
