# Generated by Django 4.1.3 on 2022-12-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_profile_about_alter_profile_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('Grill lover', 'Grill lover'), ('Picnic enthusiast', 'Picnic enthusiast'), ('Vegatarian', 'Vegatarian'), ('Meat Lover', 'Meat Lover'), ('Pro Chief', 'Pro Chief'), ('Just an average Chief', 'Just an average Chief'), ('Cooker on Holidays', 'Cooker on Holidays'), ('Alcocholic', 'Alcocholic'), ('Candy crusher', 'Candy crusher')], max_length=22, null=True, verbose_name='Choose your type'),
        ),
    ]
